### ISSUE TITLE
Rename top-level namespace to cljs-commons

### ISSUE THREAD

**Issue by oakmac** [clj-commons/humanize#32]
From [PR-31]:

> One thing I will say about this project: using `clojure.*` for a non-official project is a big no-no, and using `clojure.contrib.*` doubly so, so when this library gets overhauled, I would strongly recommend changing the top-level namespace.

I agree with this assessment by @seancorfield and think it would appropriate to change the top-level ns for this project.

Since it is planned to move to clj-commons, maybe the following:

* `clojure.contrib.humanize` --> `clj-commons.humanize.core`
* `clojure.contrib.inflect` --> `clj-commons.humanize.inflect`
* `clojure.contrib.macros` --> removed by [PR-31]

[PR-31]:https://github.com/trhura/clojure-humanize/pull/31

**Comment by hlship** [comment]
Fixed by 1deb9802460e8e1f2ab10e819b31e276bf9ed106
